image: docker:latest
services:
    - docker:dind

stages: 
  - build

build:
  stage: build
  only:
    - tags
  before_script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN
  script:
    - docker build -t de1ay/nginx-http3:latest -t de1ay/nginx-http3:$CI_COMMIT_TAG .